repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: no-commit-to-branch
        args: [--branch, master]
    -   id: pretty-format-json
        args: [--autofix]
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    # Semantically checks the code quality
    rev: 3.7.9
    hooks:
    - id: flake8
-   repo: https://github.com/asottile/seed-isort-config
    # Feeds known third party packages to isort based on our codebase. Without this
    # isort would sort things properly.
    rev: v2.1.0
    hooks:
    -   id: seed-isort-config
        args: [--application-directories, "src"]
-   repo: https://github.com/timothycrosley/isort
    # Sorts our import statements
    rev: 4.3.21-2
    hooks:
    -   id: isort
        args: [--check]
        files: \.py$
        additional_dependencies:
         - toml
-   repo: https://github.com/ambv/black
    # Formats our python code
    rev: 19.10b0
    hooks:
    - id: black
      args: [--check, --config, "pyproject.toml"]
