version: "2"

volumes:
  mongodb_data:

services:
  default:
    build: .
    env_file: .env
    command: python -u worker.py
    volumes:
      - ./src/:/app/src
  web:
    build: .
    env_file: .env
    command: python -u web.py
    ports:
      - "5000:5000"
    volumes:
      - ./src/:/app/src
  db:
    image: mongo:4
    volumes:
      - mongodb_data:/data/db/
