[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 79
known_third_party = ["Crypto", "aiohttp", "bson", "colored", "flask", "marshmallow", "marshmallow_enum", "marshmallow_oneofschema", "paramiko", "pymongo", "pytest", "sentry_sdk", "sticky_marshmallow"]
